language: python

python: '3.6'

addons:
  postgresql: '10'

  apt:
    packages:
      - postgresql-10-postgis-2.4

install:
    - pip install --upgrade -r pldp/equirements.txt

script:
    - flake8 ./pldp/*.py
    - pytest
