language: python

python: '3.6'

addons:
  postgresql: '10'

  apt:
    packages:
      - postgresql-10-postgis-2.5

install:
    - pip install --upgrade -r tests/test_requirements.txt
    - pip install -e .

script:
    - flake8 ./pldp/*.py
    - pytest
