language: python

python: '3.6'

addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
before_script:
  - psql -U postgres -c "create extension postgis"

install:
    - pip install --upgrade -r pldp/requirements.txt

script:
    - flake8 ./pldp/*.py
    - pytest
