language: python

python: '3.6'

addons:
  postgresql: '10'
  apt:
    packages:
      - postgresql-10-postgis-2.4

before_script:
  - psql -c 'create database pldp;' -U postgres
  - psql -U postgres -c "create extension postgis"

install:
    - pip install --upgrade -r pldp/requirements.txt

script:
    - flake8 ./pldp/*.py
    - pytest
