# Generated by Django 2.1.3 on 2018-12-03 12:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages_plus', '0004_auto_20171214_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full name of the agency that is conducting/posting the study.', max_length=1000)),
                ('department', models.CharField(blank=True, help_text='Specific department within the agency that is responsible for the study. Leave blank, if no such specification is necessary.', max_length=1000, null=True)),
                ('phone', models.CharField(blank=True, help_text='Direct single voice telephone number for the specified agency.', max_length=100, null=True)),
                ('email', models.EmailField(help_text="Single valid email address actively monitored by the agency's reception or inquiry desk.", max_length=254)),
                ('type', models.CharField(blank=True, help_text='Character of the type of agency that is conducting/posting the study.', max_length=255, null=True)),
                ('language', models.ForeignKey(blank=True, help_text='Main language used by the agency posting the study. Leave blank, if only British English is used to fill in the study.', null=True, on_delete=django.db.models.deletion.CASCADE, to='languages_plus.Language')),
            ],
        ),
    ]
