# Generated by Django 2.1.3 on 2019-01-29 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_choice', models.CharField(help_text='Level of detail expected by survey component', max_length=8)),
                ('basic_choice', models.CharField(blank=True, max_length=255, null=True)),
                ('detailed_choice', models.CharField(blank=True, max_length=255, null=True)),
                ('complex_choice', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenderComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_choice', models.CharField(help_text='Level of detail expected by survey component', max_length=8)),
                ('basic_choice', models.CharField(blank=True, max_length=255, null=True)),
                ('detailed_choice', models.CharField(blank=True, max_length=255, null=True)),
                ('complex_choice', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='surveycomponent',
            name='content',
        ),
        migrations.RemoveField(
            model_name='surveycomponent',
            name='name',
        ),
        migrations.AddField(
            model_name='surveycomponent',
            name='type_of_component',
            field=models.CharField(choices=[('gender', 'Gender'), ('age', 'Age'), ('mode', 'Mode'), ('posture', 'Posture'), ('activities', 'Activities'), ('groups', 'Groups'), ('objects', 'Objects'), ('geotag', 'GeoTag')], db_index=True, default='gender', help_text='Type of survey component', max_length=15),
        ),
        migrations.AddField(
            model_name='surveycomponent',
            name='age',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.AgeComponent'),
        ),
        migrations.AddField(
            model_name='surveycomponent',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.GenderComponent'),
        ),
    ]
