# Generated by Django 2.1.3 on 2019-01-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20190130_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveycomponent',
            name='total',
        ),
        migrations.AddField(
            model_name='surveyrow',
            name='total',
            field=models.IntegerField(blank=True, help_text='Indicate the number of people counted within the row. This field is not an ID, but it should be included with every survey.', null=True),
        ),
    ]
