# Generated by Django 2.1.3 on 2019-01-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20190130_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyrow',
            name='total',
            field=models.IntegerField(default=1, help_text='Indicate the number of people counted within the row. This field is not an ID, but it should be included with every survey.'),
        ),
    ]
