# Generated by Django 2.1.3 on 2019-01-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_surveycomponent_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveycomponent',
            name='detail_level',
            field=models.CharField(choices=[('basic', 'Basic choices'), ('detailed', 'Detailed choices'), ('complex', 'Complex choices')], default='basic', help_text='The level of detail that we expect in the responses', max_length=10),
        ),
        migrations.AlterField(
            model_name='surveycomponent',
            name='age',
            field=models.CharField(blank=True, help_text='Observed or reported age', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='surveycomponent',
            name='gender',
            field=models.CharField(blank=True, help_text='Observed or reported gender', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='surveycomponent',
            name='type_of_component',
            field=models.CharField(help_text='The component that is actually in use', max_length=10),
        ),
        migrations.DeleteModel(
            name='AgeComponent',
        ),
        migrations.DeleteModel(
            name='GenderComponent',
        ),
    ]
