# Generated by Django 2.1.5 on 2019-02-12 14:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Title or name of the study as given by the conducting agency.', max_length=1000, null=True)),
                ('project', models.CharField(blank=True, help_text='Title or name of the project that the study is part of. Leave blank if the study is not linked to any other project.', max_length=1000, null=True)),
                ('project_phase', models.CharField(blank=True, help_text='Project phase or stage at the time of the study. Leave blank if the study is not linked ot any other project.', max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, help_text='Date of the first survey taking place within a study.', null=True)),
                ('end_date', models.DateField(blank=True, help_text='The date of the last survey taking place within a study', null=True)),
                ('scale', models.CharField(blank=True, choices=[('district', 'District'), ('city', 'City'), ('city center', 'City center'), ('neighborhood', 'Neighborhood'), ('block scale', 'Block scale'), ('single site', 'Single site')], help_text='Approximate scale of the entire study area, irregardless of the amount of survey locations within that study area.', max_length=12, null=True)),
                ('manager_name', models.CharField(help_text='Name of the person in charge of the study', max_length=1000)),
                ('manager_email', models.EmailField(blank=True, help_text='Direct email to the person in charge of the study', max_length=254, null=True)),
                ('protocol_version', models.CharField(default='1.0', help_text='Version of the Public Life Data Protocol that the study is written in.', max_length=5)),
                ('notes', models.TextField(blank=True, help_text='Notes that regard the entirety of the study.', null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Agency')),
            ],
        ),
        migrations.CreateModel(
            name='StudyArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the study area', max_length=1000)),
                ('area', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='study',
            name='areas',
            field=models.ManyToManyField(help_text='Area geometries for surveys bundles together within one larger study. Leave blank if no such sub-division is necessary.', to='study.StudyArea'),
        ),
    ]
