# Generated by Django 2.1.5 on 2019-02-12 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pldp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyComponentActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_level', models.CharField(choices=[('basic', 'Basic choices'), ('detailed', 'Detailed choices'), ('complex', 'Complex choices')], default='basic', help_text='The level of detail that we expect in the responses', max_length=10)),
                ('posture', models.CharField(blank=True, help_text='Observed or reported activities', max_length=10, null=True)),
                ('count', models.IntegerField(default=1, help_text='Count the number of people engaging in the specified activity.')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pldp.SurveyRow')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pldp.Survey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyComponentAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_level', models.CharField(choices=[('basic', 'Basic choices'), ('detailed', 'Detailed choices'), ('complex', 'Complex choices')], default='basic', help_text='The level of detail that we expect in the responses', max_length=10)),
                ('age', models.CharField(blank=True, help_text='Observed or reported age', max_length=10, null=True)),
                ('count', models.IntegerField(default=1, help_text='Count the number of people of the specified age.')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pldp.SurveyRow')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pldp.Survey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyComponentGender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_level', models.CharField(choices=[('basic', 'Basic choices'), ('detailed', 'Detailed choices'), ('complex', 'Complex choices')], default='basic', help_text='The level of detail that we expect in the responses', max_length=10)),
                ('gender', models.CharField(blank=True, help_text='Observed or reported gender', max_length=10, null=True)),
                ('count', models.IntegerField(default=1, help_text='Count the number of people of the specified gender.')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pldp.SurveyRow')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pldp.Survey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyComponentGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_level', models.CharField(choices=[('basic', 'Basic choices'), ('detailed', 'Detailed choices'), ('complex', 'Complex choices')], default='basic', help_text='The level of detail that we expect in the responses', max_length=10)),
                ('group', models.CharField(blank=True, help_text='Observed or reported size of group', max_length=10, null=True)),
                ('count', models.IntegerField(default=1, help_text='Count the number of groups of the specified size.')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pldp.SurveyRow')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pldp.Survey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyComponentMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_level', models.CharField(choices=[('basic', 'Basic choices'), ('detailed', 'Detailed choices'), ('complex', 'Complex choices')], default='basic', help_text='The level of detail that we expect in the responses', max_length=10)),
                ('mode', models.CharField(blank=True, help_text='Observed or reported mode of transportation', max_length=10, null=True)),
                ('count', models.IntegerField(default=1, help_text='Count the number of people using the specified mode of transportation.')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pldp.SurveyRow')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pldp.Survey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyComponentObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_level', models.CharField(choices=[('basic', 'Basic choices'), ('detailed', 'Detailed choices'), ('complex', 'Complex choices')], default='basic', help_text='The level of detail that we expect in the responses', max_length=10)),
                ('object', models.CharField(blank=True, help_text='Observed or reported objects or animals carried', max_length=10, null=True)),
                ('count', models.IntegerField(default=1, help_text='Count the number of people carrying the specified object or animal.')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pldp.SurveyRow')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pldp.Survey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyComponentPosture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_level', models.CharField(choices=[('basic', 'Basic choices'), ('detailed', 'Detailed choices'), ('complex', 'Complex choices')], default='basic', help_text='The level of detail that we expect in the responses', max_length=10)),
                ('posture', models.CharField(blank=True, help_text='Observed or reported physical posture', max_length=10, null=True)),
                ('count', models.IntegerField(default=1, help_text='Count the number of people in the specified posture.')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pldp.SurveyRow')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pldp.Survey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='surveycomponent',
            name='row',
        ),
        migrations.RemoveField(
            model_name='surveycomponent',
            name='survey',
        ),
        migrations.DeleteModel(
            name='SurveyComponent',
        ),
    ]
