# Generated by Django 2.1.5 on 2019-03-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pldp', '0002_auto_20190327_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='form_id',
            field=models.IntegerField(default=0, help_text='ID number of the form used to submit this survey.'),
            preserve_default=False,
        ),
    ]
