# Generated by Django 2.1.5 on 2019-03-27 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pldp', '0003_survey_form_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_level', models.CharField(choices=[('basic', 'Basic choices'), ('detailed', 'Detailed choices'), ('complex', 'Complex choices')], default='basic', help_text='The level of detail that we expect in the responses', max_length=255)),
                ('name', models.CharField(help_text='The unique identifier of this survey question', max_length=500)),
                ('label', models.CharField(help_text='The text of this survey question', max_length=500)),
                ('type', models.CharField(help_text='The type of this survey question', max_length=500)),
                ('position', models.IntegerField(help_text='The position of this question in the survey', max_length=500)),
                ('saved_data', models.CharField(help_text='The submitted answer to this survey question', max_length=500)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pldp.SurveyRow')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
