# Generated by Django 2.1.5 on 2019-03-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pldp', '0004_surveycomponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveycomponent',
            name='position',
            field=models.IntegerField(help_text='The position of this question in the survey'),
        ),
    ]
