# Generated by Django 2.1.5 on 2019-05-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pldp', '0006_auto_20190402_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyrow',
            name='total',
            field=models.IntegerField(blank=True, help_text='Indicate the number of people counted within the row. This field is not an ID, but it should be included with every survey.', null=True),
        ),
    ]
