# Generated by Django 2.1.5 on 2019-05-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pldp', '0009_auto_20190514_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='type',
            new_name='geometry_type',
        ),
    ]
