# Generated by Django 2.1.5 on 2019-05-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pldp', '0010_auto_20190514_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='geometry_type',
            field=models.CharField(blank=True, choices=[('line', 'line'), ('area', 'area')], help_text='Indication of whether the location is intended for counts of people moving (across a line), or whether it is intended for counts of people staying (within an area).', max_length=4),
        ),
    ]
