# Generated by Django 2.1.5 on 2019-06-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pldp', '0011_auto_20190520_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='study',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
